config/routes.rb
Rails.application.routes.draw do

  resources :tasks

  root "tasks#index"

  post "tasks/:id/toggle", to: "tasks#toggle"
  get "tasklog", to: "tasks#tasklog"
  get "import", to: "tasks#import"
  get "export", to: "tasks#export"
  get "purge", to: "tasks#purge_completed"
  post "batch_add", to: "tasks#batch_add"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def index
    @tasks = Task.all
    @task = Task.new
  end

  def import
    render "import"
  end

  def batch_add
    # TODO Refactor addition logic to avoid duplicating the code
    task_array = import_params[:tasklist].split(/\r?\n/)
    creation_date_pattern = /(?<=^|\([A-Z]\)[ ])((\d{4})-(\d{2})-(\d{2}))(?=[ ]|$)/

    task_array.each do |task_body|

      task_body.lstrip!

      creation_date = task_body.match(creation_date_pattern)
      task_body.gsub!(creation_date_pattern, "")

      task = Task.new(description: task_body)

      if import_params[:add_dates].eql?("1")
        task.creation_time = Time.now.to_datetime
      end

      unless creation_date.nil?
        task.creation_time = DateTime.strptime(creation_date[0] << "T00:00:00", "%Y-%m-%dT%H:%M:%S")
      end

      unless task.save
        format.html { redirect_to tasks_url, status: :unprocessable_entity }
      end
    end
    redirect_to tasks_url

  end

  def create

    creation_date_pattern = /(?<=^|\([A-Z]\)[ ])((\d{4})-(\d{2})-(\d{2}))(?=[ ]|$)/
    creation_date = task_params[:description].match(creation_date_pattern)

    @task = Task.new(task_params)
    if creation_date.nil?
      @task.creation_time = Time.now.to_datetime
    else
      task_params[:description].gsub!(creation_date_pattern, "")
      @task.creation_time = DateTime.strptime(creation_date[0] << "T00:00:00", "%Y-%m-%dT%H:%M:%S")
    end

    respond_to do |format|
      if @task.save
        format.html { redirect_to tasks_url }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  def toggle
    @task = Task.find(params[:id])

    if @task.completed
      completion_time = nil
    else
      completion_time = Time.now.to_datetime
    end

    @task.update(completed: params[:completed], completion_time: completion_time)

    render json: { message: "Success" }
  end

  def edit
    @task = Task.find(params[:id])
  end

  def update
    @task = Task.find(params[:id])
    respond_to do |format|
      if @task.update(task_params)
        format.html { redirect_to tasks_url }
      else
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @task = Task.find(params[:id])
    @task.destroy
    redirect_to request.referrer
  end

  def tasklog
    @tasks = Task.where(completed: true)
    render "tasklog"
  end

  # There *HAS* to be a better way, right?
  def export
    priority_pattern = /^(\([A-Z]\)[ ])/
    all_tasks = ""

    Task.where(completed: false).each do |task|
      task_text = task[:description]
      priority = task_text.match(priority_pattern)
      task_text.gsub!(priority_pattern, "")

      unless priority.nil?
        all_tasks << priority[0]
      end
      unless task[:creation_time].nil?
        all_tasks << task[:creation_time].to_datetime.strftime("%Y-%m-%d") << " "
      end
      all_tasks << task_text << "\r\n"
    end
    send_data all_tasks, :filename => "todo.txt"
  end

  def purge_completed
    Task.where(completed: true).each do |task|
      task.destroy
    end
    redirect_to tasklog_path
  end

  private

  def task_params
    params.require(:task).permit(:description)
  end

  def import_params
    params.require(:task).permit(:tasklist, :add_dates)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def markdown(text)
    options = [:hard_wrap, :autolink, :no_intra_emphasis, :fenced_code_blocks, :underline, :highlight,
               :no_images, :safe_links_only, :prettify, :no_styles]
    Markdown.new(text, *options).to_html.html_safe
  end
end

app/helpers/tasks_helper.rb
module TasksHelper

  def parse_task(task_description)
    # TODO: Move patterns out of here to avoid duplication
    priority_pattern = /^(\([A-Z]\)[ ])/
    context_pattern = /(?<=^|[ ])(@[^[ ]]+)/
    project_pattern = /(?<=^|[ ])(\+[^[ ]]+)/
    markdown_link_pattern =  /^\[([\w\s\d]+)\]\(((?:\/|https?:\/\/)[\w\d.\/?=#]+)\)$/

    task_description
      .gsub(priority_pattern, '')
      .gsub(context_pattern, '<span class="context"><a href="/tasks?q=\1" target="_top">\1</a></span>')
      .gsub(project_pattern, '<span class="project"><a href="/tasks?q=\1" target="_top">\1</a></span>')
  end

  def priority(task_description)
    priority_pattern = /^(\([A-Z]\)[ ])/
    task_description.match(priority_pattern)
  end

  def contexts(tasks)
    context_pattern = /(?<=^|[ ])(@[^[ ]]+)/
    parse_tags(tasks, context_pattern)
  end

  def projects(tasks)
    project_pattern = /(?<=^|[ ])(\+[^[ ]]+)/
    parse_tags(tasks, project_pattern)
  end

  def uncompleted(tasks)
    tasks.where(completed: false)
  end

  def completed(tasks)
    tasks.where(completed: true)
  end

  def parse_tags(tasks, pattern)

    contexts = []
    tasks.each do |task|
      contexts << task.description.to_enum(:scan, pattern).map { $& }
    end
    contexts.flatten.uniq
  end

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <title>emrld.txt</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  <%= stylesheet_link_tag "bootstrap" %>
  <%= stylesheet_link_tag "responsive" %>
  <%= favicon_link_tag asset_path('favicon.ico') %>
  <%= javascript_importmap_tags %>
</head>

<body>
<%= render "shared/header" %>
<div class="container-fluid">
  <%= yield %>
</div>
<script src="https://code.jquery.com/jquery.js"></script>
</body>
</html>

app/views/shared/_header.html.erb
<div class="navbar navbar-inverse navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
      <button type="button" class="btn btn-navbar collapsed" data-toggle="collapse" data-target=".nav-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="cool-brand" href="/">emrld.txt</a>
      <div class="nav-collapse collapse" style="height: 0px;">
        <ul class="nav">
          <li><%= link_to "Import/Batch Add", import_path %></li>
          <li><%= link_to "Export", export_path %></li>
          <li><%= link_to "Tasklog", tasklog_path %></li>
        </ul>
        <%= form_tag tasks_path, :method => 'get', class: 'navbar-form pull-right', html: { autocomplete: "off" } do %>
          <%= text_field_tag :q, params[:q], placeholder: "I'm searching for..." %>
        <% end %>
      </div><!--/.nav-collapse -->
    </div>
  </div>
</div>

app/views/tasks/_form.html.erb
<%= form_with(model: task, html: { autocomplete: "off" }) do |form| %>
  <% if notice.present? %>
    <p>
      <%= notice %>
    </p>
  <% end %>
  <div>
    <%= form.text_field :description, style: "margin-bottom: 0px", placeholder: "(A) I'm planning to @context +project" %>
  </div>
<% end %>

app/views/tasks/_search.html.erb
<%= form_tag tasks_path, :method => 'get', html: { autocomplete: "off" } do %>
  <p>
    <%= text_field_tag :q, params[:q], style: "margin-bottom: 0px", placeholder: "I'm searching for..." %>
    <%= submit_tag  "Search", class: "btn", :q => nil %>
  </p>
<% end %>

app/views/tasks/_task.html.erb
<tr class="task">
  <turbo-frame id="<%= dom_id task %>
  <%= 'completed' if task.completed %>">
    <%= form_with(model: task) do |form| %>
      <td style="width: 20px;">
        <label class="checkbox">
          <%= form.check_box :completed,
                             data: {
                               id: task.id,
                               action: "tasks#toggle"
                             } %>
        </label>
      </td>
      <td>
        <span class="priority"><%= priority(task.description) %></span>
        <% if task.creation_time? %>
          <span class="created-date"><%= task.creation_time.strftime("%Y-%m-%d") %></span>
        <% end %>
        <% if task.completion_time? %>
          <span class="completed-date"><%= task.completion_time.strftime("%Y-%m-%d") %></span>
        <% end %>
        <span class="task-content"><%= parse_task(task.description).html_safe %></span>
    <% end %>
    <td>
      <div class="task-actions">
        <%= link_to "Edit", edit_task_path(task), class: "btn btn-link" %>
        <%= button_to "Delete", task_path(task),
                      method: :delete,
                      data: { "turbo-frame": "_top" },
                      class: "btn btn-link"
        %>
      </div>
    </td>
  </turbo-frame>
  </td>
</tr>

app/views/tasks/edit.html.erb
<turbo-frame id="<%= dom_id @task %>">
  <div class="edit-task">
    <%= render "form", task: @task %>
    <%= link_to "Never Mind", tasks_path %>
  </div>
</turbo-frame>

app/views/tasks/import.html.erb
<div class="import-wrapper">
  <%= form_for :task, url: batch_add_path, html: { autocomplete: "off" }, class: "import-form" do |form| %>
    <% if notice.present? %>
      <p>
        <%= notice %>
      </p>
    <% end %>
    <div>
      <%= form.text_area :tasklist, class: "margin-auto" %>
      <div style="display: inline-flex">

        <%= form.submit "Import", class: "btn btn-primary" %>
        <div class="checkbox" style="margin-top: 4px; margin-left: 1em">
          <%= form.check_box :add_dates %>
          <%= form.label "Add missing creation dates (will be set to today)" %>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/tasks/index.html.erb
<div class="row-fluid">
  <div class="span10">
    <% if params[:q] %>
      <% @tasks = uncompleted(Task.where("description LIKE ?", "%" + params[:q].strip + "%")) %>
      <h2><%= params[:q] %></h2>
    <% else %>
      <% @tasks = uncompleted(Task.all) %>
    <% end %>
    <div class="add-task">
      <%= render "form", task: @task %>
    </div>
    <div data-controller="tasks" class="tasks">
      <table class="table table-striped">
        <%= render uncompleted(@tasks) %>
      </table>
    </div>
  </div>
  <div class="span2">
    <div class="sidebar-section-head"><a href="/inbox">Inbox</a></div>
    <% if contexts(@tasks).any? %>
      <div id="accordion1">
        <div style="margin-bottom: .5em;">
          <div class="sidebar-section-head">
            <a data-toggle="collapse" data-parent="#accordion1" href="#collapseOne" id="collapseHead1">
              <span id="open1" class="toggle-triangle">▾</span>Contexts</a></div>
        </div>
        <div id="collapseOne" class="accordion-body collapse in">
          <div class="contexts">
            <% contexts(@tasks).each do |context| %>
              <div style="margin-bottom: .25em;"><%= parse_task(context).html_safe %><br></div>
            <% end %>
          </div>
        </div>
        <div style="border-bottom: 1px solid #e5e5e5;"/>
      </div>
    <% end %>
    <% if contexts(@tasks).any? and projects(@tasks).any? %>
      <div class="divider"></div>
    <% end %>
    <% if projects(@tasks).any? %>
      <div id="accordion2">
        <div style="margin-bottom: .5em;">
          <div class="sidebar-section-head">
            <a class="sidebar-section-head" data-toggle="collapse" data-parent="#accordion2" href="#collapseTwo">
              <span id="open2" class="toggle-triangle">▾</span>Projects</a></div>
        </div>
        <div id="collapseTwo" class="accordion-body collapse in">
          <div class="project">
            <% projects(@tasks).each do |context| %>
              <div style="margin-bottom: .25em;"><%= parse_task(context).html_safe %><br></div>
            <% end %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/tasks/tasklog.html.erb
<div class="row-fluid">
  <div class="span12">
    <div class="w9 margin-auto">
      <h1 style="display: inline-block">Tasklog</h1>
      <div style="display: inline-block; width: 100%; text-align: right;">
        <%= link_to "Purge completed", purge_path %>
      </div>
    </div>
    <div data-controller="tasks" class="tasks w9">
      <% if completed(@tasks).present? %>
        <table class="table table-striped">
          <%= render completed(@tasks) %>
        </table>
      <% else %>
        <div class="nothing-here">
          <p>Your tasklog is clear.</p>
        </div>
      <% end %>
    </div>
  </div>
</div>